### ISSUE TITLE
天気アイコンの商用利用について

### ISSUE THREAD

**Issue by weathersky** [ciscorn/jma-weather-images#1]
ciscorn様

初めまして、weatherskyと申します。
https://github.com/ciscorn/jma-weather-images
上記サイトはpublicなリポジトリのオープンソースになっておりますが、
天気アイコン画像を商用利用する事も可能でしょうか？

お忙しいところ申し訳ございませんが、ご返信いただければ幸いです。
よろしくお願い致します。

**Comment by ciscorn** [comment]
@weathersky 

/jma/ ディレクトリに気象庁さまの画像が含まれておりますが、それ以外の画像は商用でも自由に利用して頂いてかまいません。どうぞよろしくお願いします。

**Comment by weathersky** [comment]
ciscorn様

早速のご返答、誠にありがとうございます。
画像利用の件、承知致しました。

ありがたく使用させていただきます。
ありがとうございました。
